### ISSUE TITLE
Population of categories in the database

### ISSUE THREAD

**Issue by hexydec** [digpen/SkillsMap#6]
The categories of the database needs setting, grouping and inserting

**Comment by sophiedennis** [comment]
Did you have any luck contacting Craig about this?

**Comment by hexydec** [comment]
I have had no reponse from either twitter or GitHub messages

**Comment by sophiedennis** [comment]
:(  OK, suggest we forget getting the original from Craig and recreate the categories ourselves from the skillmap spreadsheet. Do you still have access to it?

**Comment by web-engineer** [comment]
Hi guys, what is this your after? Have got some models from the day but I thought will had taken a different direction - if you need anything from me feel free to call/email. I dont often check my Twitter account though I do get the github messages in my mail. I've been swamped of late so haven't had a great deal of time to assist.

**Comment by hexydec** [comment]
Hi Craig,

Did you create a list of categories for the skillsmap application? I can't find it anywhere.

Will

**Comment by web-engineer** [comment]
No sure if this will work...

Attached are the PDF's of the database models that we hatched on the 
day... Dont think we actually wrote a list up, we just looked at a model 
to suit.

//Craig
